config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  root "jobs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job.rb
class Job < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

    def index
       @jobs = Job.all.order('created_at ASC') 
    end

    def new
        @job = Job.new
    end

    def create
        @job = Job.new(job_params)
        if @job.save
            redirect_to @job
        else
            render 'new'
        end
    end

    def show
        @job =Job.find(params[:id])
    end

    def edit
        @job = Job.find(params[:id])
    end

    def update
        @job = Job.find(params[:id])

		if @job.update(params[:job].permit(:name, :contract_amount, :contract_date, :status))
			redirect_to @job
		else
			render 'edit'
		end
    end
    
    def destroy
        @job = Job.find(params[:id])
        @job.destroy        
        redirect_to root_path
    end



    private

        def job_params
            params.require(:job).permit(:name, :contract_amount, :contract_date, :status)
        end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>
    <p>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
     </p>

    <p>
        <%= f.label :contract_amount %><br>
        <%= f.text_field :contract_amount %>
    </p>

    <p>
        <%= f.label :contract_date %><br>
        <%= f.date_field :contract_date %>
    </p>

    <p>
        <%= f.label :status%><br>
        <%= f.check_box :status %>
    </p>

<div class="col-auto">
     <%= f.submit class: "btn btn-primary btn-sm" %>
</div>

      
<% end %>

app/views/jobs/edit.html.erb
<div id="page_wrapper">
    <h1>Edit Job</h1>

    <%= render 'form' %>
</div>

app/views/jobs/index.html.erb
<div class="container">
<h1>DDM Jobs</h1>
  <div class="row">
    <div class="col-9">  
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th scope="col">Job Name</th>
            <th scope="col">Contract Amount</th>
            <th scope="col">Contract Date</th>
            <th scope="col">Status</th>


          </tr>
        </thead>
          <tbody>





            <% @jobs.each do |job| %>       
                 <tr>
          
                      <td><%= link_to job.name,job %></td>
                      <td><%= number_to_currency(job.contract_amount) %></td>
                      <td><%= job.contract_date%></td>
                      <td><%= job.status%></td>
                      
                  </tr>
            <% end %>
        </tbody>
      </table>
      </div>
  </div>
  <%= link_to "New Job", new_job_path(@job), :class=>"btn btn-primary btn-sm" %>
</div>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= form_for :job, url: jobs_path do |f| %>
    <p>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
     </p>

    <p>
        <%= f.label :contract_amount %><br>
        <%= f.text_field :contract_amount %>
    </p>

    <p>
        <%= f.label :contract_date %><br>
        <%= f.date_field :contract_date %>
    </p>

    <p>
        <%= f.label :status %><br>
        <%= f.text_field :status %>
    </p>

    <p>
        <%= f.submit %>
    </p>

<% end %>

app/views/jobs/show.html.erb
<h1 class="name">
    <%= @job.name %>
</h1>

<p class="contract_amount">
    <%= number_to_currency(@job.contract_amount, :precision => 2) %>
</p>

<p class="contract_date">
    <%= @job.contract_date.strftime("%m/%d/%Y")  %>
</p>

<p class="Status">
    <%= @job.status %>
</p>

<p>
    <%= link_to "All Jobs", jobs_path, class: 'btn btn-primary'%> 
    <%= link_to "Edit", edit_job_path(@job),class: 'btn btn-primary' %> 
    <%= link_to "Delete", job_path(@job), class: 'btn btn-danger', data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    
</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DDM Log</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
    
    <%= javascript_include_tag "turbo", type: "module" %>
    <%= javascript_importmap_tags %>

  </head>
  <body>
  <div class="container">
     <div class="row">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Distinctive Doors and More Job Log</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/jobs/new">New Job</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>


            </ul>
          </div>
        </div>
      </nav>

      </div>
    </div>
  </body>

</html>

  <body>

    <%= yield %>
  </body>
</html>